### ISSUE TITLE
Crashes if /system is not already mounted

### ISSUE THREAD

**Issue by Shadow53** [ale5000-git/tingle#16]
Attempting to run tingle from TWRP without /system mounted (the default behavior, it seems) results in this crash message:

```
Traceback (most recent call last):
  File "main.py", line 396, in <module>
    brew_input_file(mode, chosen_one)
  File "main.py", line 263, in brew_input_file
    output = subprocess.check_output([DEPS_PATH["adb"], "-s", chosen_one, "pull", "/system/framework/framework.jar", "."], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', 'ZX1G22M5TH', 'pull', '/system/framework/framework.jar', '.']' returned non-zero exit status 1
```

Perhaps including a couple of adb commands to check if /system is mounted at all before pulling the framework.jar?

On a side note, I saw that Tingle correctly remounts /system as rw if it was mounted ro, but I got this message. Everything worked out and the system got patched, but the DEBUG message is confusing:
**\* Remounting /system...
      DEBUG: remount of vendor failed: Success
remount failed

**Comment by ale5000-git** [comment]
The thing of unmounted /system is a know issue, I will fix it but I have had no time yet.

The debug message just show what the adb command report (it isn't a message written by me), the problem of confusing message is a problem of Android itself (not sure if it is in adb for the pc or in the recovery code).

**Comment by ale5000-git** [comment]
It should be fixed, please try the latest version and report back.
