### ISSUE TITLE
Add information for macOS

### ISSUE THREAD

**Issue by moodl** [ale5000-git/tingle#17]
Maybe you should add the information that you have to install 7zip on macOS in the Terminal. 

https://superuser.com/questions/548349/how-can-i-install-7zip-so-i-can-run-it-from-terminal-on-os-x

**Comment by ale5000-git** [comment]
I will do something in the near future.

**Comment by ale5000-git** [comment]
@moodl

Could you please try the commands that I have described in the README.md and tell me if they are working correctly to install dependencies?
