### ISSUE TITLE
Unable to execute from recovery

### ISSUE THREAD

**Issue by JonnyTech** [ale5000-git/tingle#18]
I have a phone running CM13 with CM recovery
Booted to recovery and sideloaded CM update zip
Then went to Advanced >> Mount /system
When trying to run Tingle get the following error:

~~~
$ python3 main.py 
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Linux 4.8.0-1-amd64 (linux)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-k1k5i_h3
 *** Selected device: WbSPARKPJH0025693
 *** Pulling framework from device...
Traceback (most recent call last):
  File "main.py", line 396, in <module>
    brew_input_file(mode, chosen_one)
  File "main.py", line 263, in brew_input_file
    output = subprocess.check_output([DEPS_PATH["adb"], "-s", chosen_one, "pull", "/system/framework/framework.jar", "."], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', 'WbSPARKPJH0025693', 'pull', '/system/framework/framework.jar', '.']' returned non-zero exit status 1
~~~

What am I doing wrong?

**Comment by ale5000-git** [comment]
Can you please run `adb pull /system/framework/framework.jar .` from the pc and tell me what it say?

**Comment by JonnyTech** [comment]
From recovery or normal mode?

**Comment by ale5000-git** [comment]
Sorry to be late but I was busy, put the phone in recovery and then from the pc run the above command that try to get framework.jar from the phone to the pc.

**Comment by JonnyTech** [comment]
Thanks for the reply. If I remember correctly, I had to mount system, pull the file manually, work on it offline, then push it back. Using the script produced the error so I assume that the pull command did not provide a correct exit code. I have updated TWRP then since so I will try it again the next time that I have to patch my system.

**Comment by valpackett** [comment]
When executing in recovery on my Nexus 5X with TWRP 3.0.2-2, the tingle script just gets stuck on `adb wait-for-device` (after rooting adb). Commenting out `subprocess.check_call([DEPS_PATH["adb"], "-s", chosen_device, "wait-for-device"])` makes everything work!

(UPDATE: it's already been reported as #21)

**Comment by ale5000-git** [comment]
It should be fixed, please try the latest version and report back.

**Comment by ale5000-git** [comment]
It should be fixed, please try the latest version and report back.

**Comment by ale5000-git** [comment]
@JonnyTech: It should be fixed, please try the latest version and report back.

**Comment by ale5000-git** [comment]
It should probably be fixed in the latest version, please try it and report back when you have time.
