### ISSUE TITLE
ERROR: Missing executable => 7za

### ISSUE THREAD

**Issue by pabloportugues** [ale5000-git/tingle#20]
When executing the command, got the following error:
```
ERROR: Missing executable => 7za
ERROR CODE: 65
```

I'm running OSX and from the looks of the files in the tools folder, I guess something is missing for OSX.

**Comment by ale5000-git** [comment]
You need to have p7zip installed on OSX

**Comment by pabloportugues** [comment]
Yup, that worked like a charm! If possible please update the readme.me, maybe I was the only one having problems, but hey, at least no one else would make it again. :)
Thanks!

**Comment by gan3sh500** [comment]
I get this on Ubuntu but I have the latest p7zip.

**Comment by ale5000-git** [comment]
On Linux they have a different meaning, the one need on Linux is p7zip-full (not p7zip).

**Comment by ale5000-git** [comment]
@gan3sh500: On Linux they have a different namings, the one needed on Linux is p7zip-full (not p7zip).

**Comment by ale5000-git** [comment]
@bytemybits @gan3sh500

Could you please try the commands that I have described in the README.md and tell me if they are working correctly to install dependencies?
