### ISSUE TITLE
LineageOS: microg shows UnifiedNlp not registered in System

### ISSUE THREAD

**Issue by Nutomic** [ale5000-git/tingle#23]
Tingle didn't show any error, and everything else shows as okay in microg (including signature spoofing). Device restart did not help. Any idea how to fix this?

[Screenshot](https://i.imgur.com/kMP0upu.png)

Device: LG G4
Android version: LineageOS 14.1-20170131-NIGHTLY
microg version: 0.2.4-55-g4c4086a

**Comment by ale5000-git** [comment]
@LineageOS: Tingle currently only add support for signature spoofing (maybe in the future I can add other things but not currently).

So this error isn't related to Tingle, you should report in the proper place.

PS: This usually happen when you install it as user app, on Android 7+ it should be installed as system app (or alternatively you can patch your ROM - Tingle doesn't support this type of patch currently).

**Comment by ale5000-git** [comment]
@Nutomic: Tingle currently only add support for signature spoofing (maybe in the future I can add other things but not currently).

So this error isn't related to Tingle, you should report in the proper place.

PS: This usually happen when you install the app as user app, on Android 7+ it should be installed as system app (or alternatively you can patch your ROM - Tingle doesn't support this type of patch currently).

**Comment by Nutomic** [comment]
So this is a bug in microg? Or not a bug at all? I'm actually not sure what it means :D

**Comment by ale5000-git** [comment]
@Nutomic: No, it is a feature of Android 7 and higher.
Location providers are allowed only as system app.

**Comment by Nutomic** [comment]
I see, thanks :)

**Comment by ale5000-git** [comment]
For reference to everyone that comes here searching for a solution, the easiest way to fix this problem is to use [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360)

PS: It is also possible to recompile the ROM with a patch but it is easier the first method.
