### ISSUE TITLE
work great

### ISSUE THREAD

**Issue by ghost** [ale5000-git/tingle#24]
Work good Using Qphyton3 from android market for patching smali and used apktool on android to finish compiling smali.

**Comment by ale5000-git** [comment]
What do you mean?
There isn't any need "to finish compiling smali", the tool do everything automatically.

**Comment by ghost** [comment]
I was able to patch the smali without using a computer using Qphyton3.apk from android market and from androidfilehost.com apktool-x.apk that run on android Qphyton3.apk is able to patch smali but that's far it gets and used apktool-x.apk to finish compiling it back to framework.apk rename back to framework.jar

**Comment by ale5000-git** [comment]
@frankie801: It may take up to 3 hours to reassemble, maybe you haven't wait enough.
Or if there is an error please post it.

**Comment by ale5000-git** [comment]
@frankie801: It may take up to 3 hours to finish (including re-assembling the file), maybe you haven't waited enough.
It isn't yet optimized to run inside a phone (although it works perfectly).

If there is an error please open another issue.
