### ISSUE TITLE
Patching failed on windows

### ISSUE THREAD

**Issue by eldowin** [ale5000-git/tingle#25]
Hello, I tried using tingle with my installation of Windows 7 and get following error:

I installed Java and ADB correctly before, enabled USB Debugging on my Android Smartphone, allowed root access for ADB.

```
Traceback (most recent call last):
File "main.py", line 405, in <module>
brew_input_file(mode, chosen_one)
File "main.py", line 264, in brew_input_file
output = subprocess.check_output([DEPS_PATH["adb"], "-s", chosen_one, "pull", "/system/framework/framework.jar", "."]
File "C:\Python27\lib\subprocess.py", line 390, in __init__ errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 640, in _execute_child startupinfo)
WindowsError: [Error 2] The system can't file the corresponding file
```

I'd be really happy about some help.

**Comment by ale5000-git** [comment]
@eldowin: What happens if you run manually from command prompt this?
`adb pull /system/framework/framework.jar local_folder`

PS: Replace "local_folder" with a name of an existing folder on your pc

**Comment by georgedorn** [comment]
I had this problem when adb.exe and AdbWinApi.dll were not in my PATH.  My quick fix was to copy them into the tingle main dir.

**Comment by ale5000-git** [comment]
@eldowin: Could you please try the latest version and report back?

**Comment by ale5000-git** [comment]
Now it display a proper error message explaining the problem, please try it and report back when you have time.
