### ISSUE TITLE
libdpframework.so

### ISSUE THREAD

**Issue by JonnyTech** [ale5000-git/tingle#26]
Does tingle modify /system/lib64/libdpframework.so?

I have an [issue with SD Maid](https://github.com/d4rken/sdmaid-public/issues/785) which may be linked.

Will investigate but thought that I would ask first.

**Comment by ale5000-git** [comment]
Hi, it currently doesn't modify anything beside framework.jar (and I will surely never modify libdpframework.so)

**Comment by ale5000-git** [comment]
@JonnyTech: Have you found the cause?

**Comment by JonnyTech** [comment]
It was a problem with my ROM, sorry for not replying.
