### ISSUE TITLE
Unable to use Tingle on certain ROMs without .dex files

### ISSUE THREAD

**Issue by Ra72xx** [ale5000-git/tingle#28]
I try to use Tingle on ROMs from this site:
http://download.jesec.io/
These are unofficial for the S7, but official LineageOS ROMs have the same problem.

Tingle can't deal with those ROMs as framework.jar does not contain .dex files. It assumes they are odexed.
Un-odexer tools cannot deal with the ROMs, too, as they don't contain .odex files. So they are recognized as already unodexed.

I already used a modified stock ROM (called SuperMan) on this S7. Tingle deals with that one flawlessly.

I'm now a bit at a loss. Am I doing something completely wrong with the AOSP ROMs?

**Comment by Ra72xx** [comment]
Never mind. Found out myself thet "odexed" must not mean that .odex files are present, but also .oat files can contain this data.

**Comment by ale5000-git** [comment]
Duplicate of #2.
