### ISSUE TITLE
don't overwrite backup file

### ISSUE THREAD

**Issue by anarcat** [ale5000-git/tingle#29]
i got in this bad situation here where i patched multiple times. eventually, i wanted to back to the original non-spoofed signature, but because i ran tingle multiple times, the `.backup` file now refers to an already patched version tingle had downloaded from the phone... 

it would seem preferable to rotate those backups or at least not overwrite them to avoid dataloss.

**Comment by ale5000-git** [comment]
@anarcat: Tingle do not create or touch the backup file if the new file is already patched, try it.

PS: I have an idea to improve the backup of multiple devices, stay tuned.

**Comment by anarcat** [comment]
hmm... well then, the restore doesn't work. i have reflashed my device with the latest CM nightly i could get my hands on and microg still believes signature spoofing is enabled. so i trusted using `adb push` to set the `.backup` file and that didn't work either... maybe there's something i'm doing wrong?

**Comment by ale5000-git** [comment]
@anarcat: You need to run `adb root` and `adb remount` before `adb push`.

PS: You also need to clean dalvik/art cache and restart the phone.
PS2: I'm not sure but maybe microG cache the result of the check, have you tried to check it also with another app?

**Comment by anarcat** [comment]
understood, i'll try again. i have tried with other apps, not sure which one i would try....

i guess that since the .backup file is not overwritten, this is not a bug... so i'll just close this for now.

**Comment by ale5000-git** [comment]
@anarcat: With the latest change the backup isn't overwritten also if you patch a different phone.

PS: To test signature spoofing you can also use [this](https://github.com/Lanchon/sigspoof-checker).
