### ISSUE TITLE
64-bit phones support

### ISSUE THREAD

**Issue by ale5000-git** [ale5000-git/tingle#3]
Need testing on 64-bit phones since I don't have any 64-bit phone.

**Comment by ShapeShifter499** [comment]
This doesn't have 64-bit support?

**Comment by ShapeShifter499** [comment]
Doesn't seem to work on my Moto X Pure running the Dec 25th 2016 build of Cyanogenmod 14.1 (last build before LineageOS), this is a 64 Bit phone.   It boot loops before I can unlock my phone or do anything, I cannot even get a log. Things seem ok once I load back the default framework.jar back.

**Comment by ale5000-git** [comment]
@ShapeShifter499: Could you please upload your original framework.jar?

**Comment by ShapeShifter499** [comment]
I cannot any more, I went ahead and compiled my own copy of LineageOS and patched it.

**Comment by ShapeShifter499** [comment]
If you download the official CM or LineageOS zip for Moto X Pure, code name Clark. It's in there

**Comment by JonnyTech** [comment]
Works perfectly with ARM64 Wileyfox Spark+ CM13.1

**Comment by valpackett** [comment]
Works perfectly with Nexus 5X Lineage OS.

**Comment by ale5000-git** [comment]
Thanks for all the reports, I can consider it working correctly.

If anyone is having any problem, please open a new ticket.
