### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by breversa** [ale5000-git/tingle#33]
Hi,

Coming from https://github.com/microg/android_packages_apps_UnifiedNlp/issues/133, I wanted to give the unofficial microG installer a try (from https://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360).

Since I'm using LineageOS 14.1, I first need to add signature spoofing, so i came here to try Tingle.

I downloaded the current version, but here's the output :
`python main.py
MENU
    1 - Patch file from a device (adb)
    2 - Patch file from the input folder
> 1
 *** OS: Linux 4.10.0-22-generic (linux)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-sCi2uB
 *** Selected device: ????????????
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    OUTPUT_PATH = os.path.join(SCRIPT_DIR, "output", SELECTED_DEVICE)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)**`

That must be some kind of UTF-8 encoding issue, right ?

**Comment by ale5000-git** [comment]
@breversa: Probably.

**Comment by ale5000-git** [comment]
Please try the latest version, it should fix the problem.

**Comment by breversa** [comment]
Getting closer :

```
$ sudo python main.py
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Linux 4.10.0-22-generic (linux)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-tlh737
 *** Selected device: LGH81563e0706b
Traceback (most recent call last):
  File "main.py", line 404, in <module>
    OUTPUT_PATH = os.path.join(SCRIPT_DIR, "output", SELECTED_DEVICE)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

**Comment by ale5000-git** [comment]
@breversa: Please try the latest version and report back :)

**Comment by ale5000-git** [comment]
@breversa: Please try the latest version and report back :)

**Comment by breversa** [comment]
Yes, I will try this week-end. Thank you ! :)

**Comment by breversa** [comment]
It works ! :D

```
$ sudo python main.py 
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Linux 4.10.0-24-generic (linux)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-AM5WAn
 *** Selected device: LGH81563e0706b
 *** Pulling framework from device...
      DEBUG: 4643 KB/s (6590396 bytes in 1.386s)
 *** Decompressing framework...
      DEBUG: Decompressing framework.jar
 *** Disassembling classes...
      DEBUG: Disassembling framework/classes.dex
 *** Patching...
 *** Detected: Android 7.x / Android 6.0.x / CyanogenMod 13-14
 *** Patching succeeded.
 *** Reassembling classes...
      DEBUG: Assembling out/classes.dex
 *** Recompressing framework...
      DEBUG: Compressing framework.jar
 *** Copying the patched file to the output folder...
 *** Rooting adbd...
      DEBUG: restarting adbd as root
 *** Unlocked ADB: True
 *** Remounting /system...
      DEBUG: remount succeeded
 *** Pushing changes to the device...
      DEBUG: 7663 KB/s (6493638 bytes in 0.827s)
 *** All done! :)

Your original file is present at /home/…/Tingle/tingle-master/output/LGH81563e0706b/framework.jar.backup

If your device bootloop, please run this command on the pc when the connected device is inside recovery:
adb push "/home/…/Tingle/tingle-master/output/LGH81563e0706b/framework.jar.backup" /system/framework/framework.jar
```

**Comment by ale5000-git** [comment]
Good :)
