### ISSUE TITLE
Need framework.jar from Android O

### ISSUE THREAD

**Issue by ale5000-git** [ale5000-git/tingle#34]
I need `/system/framework/framework.jar` from Android O for testing.

If you want to help me, send me the file please.

**Comment by HawaiiBeach** [comment]
Edit: Link removed.

**Comment by ale5000-git** [comment]
It seems to work, thanks.

**Comment by HawaiiBeach** [comment]
Woops! That's from Android N.. BTW I did this on my oneplus one running [Unofficial LineageOS 14.1](https://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-lineageos-14-1-3-t3626403), ended up in a bootloop

**Comment by ale5000-git** [comment]
I have managed to found one from Android 8 and fortunately it works as is, so this issue is closed.

**Comment by HawaiiBeach** [comment]
Welp how do I post a logcat?

**Comment by ale5000-git** [comment]
I have managed to found one from Android 8 and fortunately it works as is, so this issue is closed.

@ElPumpo: The is a guide to use logcat is [here](https://forum.xda-developers.com/showthread.php?t=2141817).

**Comment by ale5000-git** [comment]
@ElPumpo: There is a guide to use logcat [here](https://forum.xda-developers.com/showthread.php?t=2141817).

Can you please open another issue for the bootloop and post a logcat?
