### ISSUE TITLE
framework.jar is tiny

### ISSUE THREAD

**Issue by JonnyTech** [ale5000-git/tingle#36]
My new ROM contains a very small framework.jar file:

```
user@computer:/mnt/img/framework$ find . -ls |grep framework
      826   4344 -rw-r--r--   1 root     root      4448256 Dec 31  2008 ./arm/boot-framework.art
      827  36716 -rw-r--r--   1 root     root     37595032 Dec 31  2008 ./arm/boot-framework.oat
      832     28 -rw-r--r--   1 root     root        28672 Dec 31  2008 ./arm/boot-mediatek-framework.art
      833    276 -rw-r--r--   1 root     root       280812 Dec 31  2008 ./arm/boot-mediatek-framework.oat
      859   6560 -rw-r--r--   1 root     root      6717440 Dec 31  2008 ./arm64/boot-framework.art
      860  42756 -rw-r--r--   1 root     root     43778800 Dec 31  2008 ./arm64/boot-framework.oat
      865     36 -rw-r--r--   1 root     root        36864 Dec 31  2008 ./arm64/boot-mediatek-framework.art
      866    288 -rw-r--r--   1 root     root       293280 Dec 31  2008 ./arm64/boot-mediatek-framework.oat
      896  19668 -rw-r--r--   1 root     root     20137075 Dec 31  2008 ./framework-res.apk
      897      4 -rw-r--r--   1 root     root          126 Dec 31  2008 ./framework.jar
      905      4 -rw-r--r--   1 root     root          310 Dec 31  2008 ./mediatek-framework.jar
```

Running tingle:

```
user@computer:/tmp/tingle-master$ ./main.py 
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Linux 4.11.0-1-amd64 (linux)
 *** Python: 2.7.13 (64 bit)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-_lXrCz
 *** Selected device: CE7P8LKRZHAAYLCI
 *** Pulling framework from device...
      DEBUG: [100%] /system/framework/framework.jar
 *** Device SDK: 24
 *** Decompressing framework...
      DEBUG: Decompressing framework.jar
 *** Disassembling classes...

ERROR: No dex file(s) found, probably the ROM is odexed.

ERROR CODE: 86
user@computer:/tmp/tingle-master$ 

```

There are no .odex files. What am I doing wrong?

**Comment by ale5000-git** [comment]
I really have to write a wiki about this :)

The .odex files are no longer used for the odexed ROM, so looking for them is pointless.
It is safer to look in the opposite way, extract framework.jar and if you do not find a dex file then the ROM is odexed and you have to deodex it.

**Comment by JonnyTech** [comment]
Thanks, can you recommend a tool for deodexing? I cannot find any that work with Linux for Nougat.

**Comment by ale5000-git** [comment]
Look at here: #10.

**Comment by JonnyTech** [comment]
Thanks, but that is a Windows tool :(

**Comment by ale5000-git** [comment]
Unfortunately I don't know and I don't have an odexed ROM to test, but in the future (no ETA yet) I will write a tool to deodex.

**Comment by JonnyTech** [comment]
Thanks again, I shall try something else then. To clarify, what is the difference or benefits of odexed vs deodexed?

**Comment by ale5000-git** [comment]
For me there is mostly no benefit at all.

On first run:
- If the ROM is deodexed (less size taken on the system partition) it must optimize files and store them in the dalvik/ART cache on first run and this take longer
- If the ROM is odexed (more size taken on the system partition) it just start as is on first run

On second run and others run:
- The same in both cases

So just for taking less time on first run we incur in a lot of additional problems.

**Comment by ale5000-git** [comment]
Duplicate of #2.
