### ISSUE TITLE
Android 7 bootloop + logcat

### ISSUE THREAD

**Issue by ElPumpo** [ale5000-git/tingle#37]
[logcat.txt](https://github.com/ale5000-git/tingle/files/1187279/logcat.txt)
Restoring the `framework.jar` doesn't help either

```
07-31 12:58:20.804  1154  1154 I dex2oat : /system/bin/dex2oat --compiler-filter=interpret-only -j2
07-31 12:58:20.804  1154  1154 E cutils-trace: Error opening trace file: No such file or directory (2)
07-31 12:58:20.848  1154  1154 I dex2oat : dex2oat took 45.193ms (threads: 2) arena alloc=7KB (7912B) java alloc=69KB (7
0856B) native alloc=1043KB (1068864B) free=1516KB (1552576B)
07-31 12:58:20.880   855   855 I PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/com.google.android.
apps.maps-1/base.apk pkg=com.google.android.apps.maps isa=arm vmSafeMode=false debuggable=false target-filter=verify-pro
file oatDir = /data/app/com.google.android.apps.maps-1/oat sharedLibraries=null
07-31 12:58:20.921  1157  1157 E cutils-trace: Error opening trace file: No such file or directory (2)
07-31 12:58:20.943  1157  1157 I dex2oat : /system/bin/dex2oat --compiler-filter=verify-profile -j2 --profile-file-fd=7
07-31 12:58:23.838  1157  1157 I dex2oat : Large app, accepted running with swap.

**Comment by ale5000-git** [comment]
Can you please try to wipe the dalvik/ART cache completely, restart and wait (also taking a logcat when it start)?

It may take a lot to start after wiping the dalvik/ART cache so do it when you have at least 1 hour.

**Comment by HawaiiBeach** [comment]
Yea... sorry but I don't feel like doing so.

**Comment by ale5000-git** [comment]
The dalvik/ART cache is just the cache where are stored the optimized apps, it doesn't contain your data.
It will just re-optimize them the first time you start the phone.

It is an operation that must be done every time you change something like patching system files.

**Comment by HawaiiBeach** [comment]
I know what the runtime cache is

> It is an operation that must be done every time you change something like patching system files.

That's not true, using Haystack I didn't have to clear the cache, just patch files and put em' back.
It's just that, I don't feel like doing all that with the risk of yet another bootloop now that I got it working.

**Comment by ale5000-git** [comment]
Does it works now?

**Comment by HawaiiBeach** [comment]
I havent tested, closed issue as it looks abandoned.

**Comment by ale5000-git** [comment]
I never really abandon anything, even after 20 years, but currently I cannot reproduce it.

**Comment by Mikdadali** [comment]
hey same issue here
how to solve that building for violet device
