### ISSUE TITLE
ADB from recovery

### ISSUE THREAD

**Issue by ZJaume** [ale5000-git/tingle#39]
Can Tingle patch with adb started from TWRP Recovery?

**Comment by ale5000-git** [comment]
If you mean use it from PC when the phone is in the recovery yes instead if you mean run directly from recovery potentially yes but you have to add a python executable for Android and a script to load it and put everything in a flashable zip.

**Comment by ZJaume** [comment]
Ok, Thanks! I mean run from PC when the phone is in recovery. My purpose is to run it after LOS OTA updates before rebooting into system.

**Comment by JonnyTech** [comment]
Note that the system partition may be unmounted so either mount from TWRP interface or from terminal.

**Comment by ale5000-git** [comment]
@JonnyTech: The latest version automatically mount the partition so it is no longer needed doing it manually, ref: #16

**Comment by ale5000-git** [comment]
Since the question was resolved I'm closing it now, if there are other questions please open a new issue.
