### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by ale5000-git** [ale5000-git/tingle#4]
The script itself probably already works, but there are some dependencies missing on OS X and it also miss testing.

**Comment by tmaone** [comment]
I haven't really checked at all what kind of dependencies might be needed for the patch, but I'd like to report a successful attempt on macOS 10.11.6 with standard homebrew and (common) friends. In fact nothing alarming from the progress log, I'm just checking now if the spoof function works for new installs. Details in the log below:

```
d..@m.. /V/e/tingle> python main.py
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Darwin 15.6.0 (darwin)
 *** Mode: 1
 *** Working dir: /var/folders/cb/88b../T/Tingle-FUk4pp
 *** Selected device: 8dxxxxxx <- (Xiaomi Gemini)
 *** Pulling framework from device...
 *** Decompressing framework...
      DEBUG: Decompressing framework.jar
 *** Disassembling classes...
      DEBUG: Disassembling framework/classes.dex
 *** Patching...
 *** Detected: Android 6.0.x / CyanogenMod 13
 *** Patching succeeded.
 *** Reassembling classes...
      DEBUG: Assembling out/classes.dex
 *** Recompressing framework...
      DEBUG: Compressing framework.jar
 *** Copying the patched file to the output folder...
 *** Rooting adbd...
      DEBUG: restarting adbd as root
      DEBUG: remount succeeded
 *** Pushing changes to the device...
 *** All done! :)
```

**Comment by ale5000-git** [comment]
Thanks for the test :)
If you have any problem feel free to create a new ticket.

**Comment by tmaone** [comment]
Sure, I will. It works flawlessly btw with new (and also updating previous) installs. Cheers.
