### ISSUE TITLE
ModuleNotFoundError: No module named 'libraries'

### ISSUE THREAD

**Issue by MazeWave** [ale5000-git/tingle#51]
> **Help Wanted**

I tried to install this library 'libraries' manually but nothing worked so far... I'm using python 3.9.4 btw.

**Comment by ale5000-git** [comment]
The python script isn't supposed to work alone, you should download the entire Tingle repository.
When you have it, it won't request nothing.

PS: `import` have various way to be used, if you do `import abc` and there is a folder called `abc` with a file called `__init__.py` it will import it.
